[target.aarch64-linux-android]
linker = "../../../android-ndk/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android27-clang"
ar = "../../../android-ndk/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"